export default {
  LOAD_GROUP_REQUEST : 'LOAD_GROUP_REQUEST',
  LOAD_GROUP_SUCCESS : 'LOAD_GROUP_SUCCESS',
  LOAD_GROUP_FAILED : 'LOAD_GROUP_FAILED',
  ADD_GROUP_SUCCESS : 'ADD_GROUP_SUCCESS',
  ADD_GROUP_REQUEST : 'ADD_GROUP_REQUEST',
  ADD_GROUP_FAILED : 'ADD_GROUP_FAILED'
}