export const GET_ALL_GROUPS = 'GET_ALL_GROUPS';
export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const ADD_GROUP_MESSAGES ='ADD_GROUP_MESSAGES';
export const DELETE_GROUP_MESSAGES='DELETE_GROUP_MESSAGES';
export const GET_ALL_GROUP_MESSAGES ='GET_ALL_GROUP_MESSAGES';
