export const ADD_FLASH_MESSAGE_SIGNUP = 'ADD_FLASH_MESSAGE_SIGNUP';
export const ADD_FLASH_MESSAGE_SIGNIN = 'ADD_FLASH_MESSAGE_SIGNIN';

export const ADD_GROUPS = 'ADD_GROUPS';
export const GET_ALL_GROUPS = 'GET_ALL_GROUPS';
export const GET_ALL_MESSAGE = 'GET_ALL_MESSAGE';
